#!/bin/python3
import RPi.GPIO as GPIO
import time
sound = 12
tilt = 26
red = 22
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(sound, GPIO.IN)
GPIO.setup(tilt, GPIO.IN)
GPIO.setup(red, GPIO.OUT)
try:
    while 1:
        SoundValue = GPIO.input(sound)
        TiltValue = GPIO.input(tilt)
        if (SoundValue == 1):
            print ("Sound Found")
            GPIO.output(red, GPIO.HIGH)
            time.sleep(0.1)
            GPIO.output(red, GPIO.LOW)
        elif (TiltValue == 0):
            print ("Tilt Detected")
            GPIO.output(red, GPIO.HIGH)
            time.sleep(0.1)
            GPIO.output(red, GPIO.LOW)
        else:
            GPIO.output(red, GPIO.LOW)
except KeyboardInterrupt:
    pass
    print("Exiting")
    GPIO.cleanup()
