#!/bin/python3
import Pi.GPIO as GPTO
import time
sound = 12
red = 22
(GPIO,setwarnings(False)
GPIO. setmode (GPIO. BCM)
GPIO. setup (sound, GPIO. IN)
GPIO.setup(red, GPIO.OUT)
def callback( sound) :
if GPIO.input (sound) :
print ("Sound Found")
GPIO.output(red, GPIO.HIGH)
time.sleep(0.1)
GPIO.output(red, GPIO. LOW)
else:
GPIO.output(red, GPIO.LOW)
GPIO. add _event_ detect (sound, GPIO.BOTH, bouncetime=300)
GPI0. add_event_callback(sound, callback)
while True:
time.sleep(1)
